version: 2.1

jobs:
  check:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: git config --global user.email "john@doe.com"
      - run: git config --global user.name "John Doe"
      - run: npm ci
      - run: npm run build
      - run: npm run test -- --coverage
      - run: npm run lint
      - store_test_results:
          path: reports
      - store_artifacts:
          path: coverage/lcov-report
          destination: coverage

workflows:
  check:
    jobs:
      - check
